services:
  - type: web
    name: granada-bot
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      playwright install
      playwright install-deps
    startCommand: gunicorn --bind 0.0.0.0:10000 granada_bot:app
    autoDeploy: true
